### PR TITLE
C2R Data Release Notes

### PR DESCRIPTION
**Pull request by JeffLCoughlin**

### CODE REVIEW

**Comment by JeffLCoughlin** [comment]
Finished off C2 notes. Going to squash and merge, and make some more minor re-organizational tweaks to the DRN page with either a direct master change or a new branch. Doug I'm kind of charging ahead here to get this out before the MMR tomorrow, so if you do get a chance to look it over and have any edits/comments or notice typos, we can update on Master. I gave it a good read-over twice though at the end so don't expect anything major.

**Comment by dacmess** [comment]
Hi Jeff, 
They look great. My only comment is that you should add a link to the pipeline release page (Release 21) and that we can delete the note under Release 22 saying that r21 is pending.

-Doug

—
Douglas Caldwell
dacmess@gmail.com

**Comment by dacmess** [comment]
They look great. My only comment is that you should add a link to the pipeline release page (Release 21) and that we can delete the note under Release 22 saying that r21 is pending.

**Comment by JeffLCoughlin** [comment]
Great catch - just commenting here for record I updated the pipeline release page in another push to address.

**Pull request merged**
