### PR TITLE
Draft post for website on interact

### PR DESCRIPTION
**Pull request by gully**

### CODE REVIEW

**Comment by gully** [comment]
Revised with feedback from @barentsen .

**Comment by gully** [comment]
Ping @barentsen, you might have committed to the wrong branch if you wanted the C18 green box to go live immediately.  In either case, this blog post now contains the changes you wanted to see--- lightkurve moved move prominently to the beginning of the post.

**Comment by barentsen** [comment]
Oops, didn't intend to push the C18 status box update here.  Will fix.

**Comment by barentsen** [comment]
:+1: Let's merge!

**Pull request merged**
