### PR TITLE
Website for Supernova Summer 2018 Hack Days

### PR DESCRIPTION
**Pull request by gully**

### CODE REVIEW

**Comment by gully** [comment]
Ready for review, @barentsen

**Comment by barentsen** [comment]
Thanks @gully!  I made a number of suggested changes and edited the title.

Main thing to do is add a paragraph about travel support.

**Comment by barentsen** [comment]
I made some edits and am happy for this version to be sent to Armin and @jessie-dotson for review.  I have uploaded it to the dev server here:

     http://keplergo.github.io/KeplerScienceWebsite/extragalactic2018/

(@gully please let me know if you think any of my edits are silly!)

**Comment by barentsen** [comment]
Merging this PR to publish the first version of the webpage to the live server.  Future correction will be made on master.  Thanks for preparing this @gully.

**Pull request merged**
